services:
  futures-signal:
    container_name: futures-signal
    build:
      context: .
      args:
        - VERSION=v1.0.1
      dockerfile: ./Dockerfile
    image: anvh2/futures-signal:v1.0.1
    volumes:
      - "./logs:/logs"
    ports:
      - "8080:8080"
    restart: always
